name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy
        run: |
          mkdir -p outputdir
          mv dist outputdir/app

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Docs
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs
          destination: outputdir/docs

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./outputdir



  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

